### ISSUE TITLE
template-variables.json removal after generation complete

### ISSUE THREAD

**Issue by AndyArcherKG** [solid-stack/scaffold-it#8]
I'm trying to understand why the `template-variables.json` file is still present post running the scaffold cmd. Is this required for another process going forward?
If not i think i would prefer to bin this off so it doesnt clutter up my projects. I tried using the post.hooks with no avail.

**Comment by pajtai** [comment]
Hi @AndyArcherKG ,

`template-variables.json` is not needed for any process. It is a human readable form of documentation of the input variables used to create a project.

To delete it after the generated project is in place, you're right that you would use a `post.hook`.

In the root of the scaffold create the file `hooks/post.hook` with the following content:

```
#!/usr/bin/env bash

rm template-variables.json
```

If the above doesn't work, please include the scaffold you are using.

Thanks!

**Comment by AndyArcherKG** [comment]
@pajtai ah i see, yeah i was having problems getting the post hook to work - it turned out i had a permissions error on the `~/.scaffold-it/` folder set it to 775 and then things started working. But thanks for the sample of the hook.
